-- Canonical installation baseline for fresh CRM installs.
-- Source: schema-only export from the current runtime database, curated for installer use.
-- Rules:
-- - no runtime data, secrets, demo users, or customer records
-- - migrations listed in InstallBaseline are treated as already absorbed by this schema
-- - `prog_procentowy` remains in `konfiguracja_systemu` as a legacy compatibility column
--   and is not used by fresh installs as the primary scheduling setting

CREATE TABLE `activity_log` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `entity_type` enum('lead','klient','task') NOT NULL,
  `entity_id` int(11) NOT NULL,
  `action` varchar(50) NOT NULL,
  `message` text DEFAULT NULL,
  `user_id` int(11) NOT NULL,
  `created_at` datetime NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `idx_activity_log_entity` (`entity_type`,`entity_id`,`created_at`),
  KEY `idx_activity_log_user` (`user_id`,`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
CREATE TABLE `admin_actions_audit` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `user_id` int(11) DEFAULT NULL,
  `username` varchar(80) DEFAULT NULL,
  `action` varchar(50) NOT NULL,
  `scope` varchar(20) NOT NULL,
  `filters_json` text DEFAULT NULL,
  `ids_json` longtext DEFAULT NULL,
  `affected_count` int(11) NOT NULL DEFAULT 0,
  `ip` varchar(45) DEFAULT NULL,
  `user_agent` varchar(255) DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `idx_admin_actions_action` (`action`),
  KEY `idx_admin_actions_created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
CREATE TABLE `cele_sprzedazowe` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `year` smallint(6) NOT NULL,
  `month` tinyint(4) NOT NULL,
  `user_id` int(11) NOT NULL,
  `target_netto` decimal(12,2) NOT NULL DEFAULT 0.00,
  `created_by_user_id` int(11) NOT NULL,
  `created_at` datetime NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_cele_sprzedazowe_period_user` (`year`,`month`,`user_id`),
  KEY `idx_cele_sprzedazowe_user` (`user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `cennik_display` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `format` varchar(100) NOT NULL,
  `opis` text DEFAULT NULL,
  `stawka_netto` decimal(10,2) NOT NULL,
  `stawka_vat` decimal(5,2) DEFAULT 23.00,
  `data_modyfikacji` timestamp NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin2 COLLATE=latin2_general_ci;
CREATE TABLE `cennik_kalkulator` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `godzina_start` time NOT NULL,
  `godzina_end` time NOT NULL,
  `stawka_netto` decimal(10,2) NOT NULL,
  `opis` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin2 COLLATE=latin2_general_ci;
CREATE TABLE `cennik_patronat` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `pozycja` varchar(255) NOT NULL,
  `stawka_netto` decimal(10,2) NOT NULL DEFAULT 0.00,
  `stawka_vat` decimal(5,2) NOT NULL DEFAULT 23.00,
  `data_modyfikacji` timestamp NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
CREATE TABLE `cennik_social` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `platforma` varchar(100) NOT NULL,
  `rodzaj_postu` varchar(100) DEFAULT NULL,
  `stawka_netto` decimal(10,2) NOT NULL,
  `stawka_vat` decimal(5,2) DEFAULT 23.00,
  `data_modyfikacji` timestamp NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin2 COLLATE=latin2_general_ci;
CREATE TABLE `cennik_spoty` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `dlugosc` enum('15','20','30') NOT NULL,
  `pasmo` enum('Prime Time','Standard Time','Night Time') NOT NULL,
  `stawka_netto` decimal(10,2) NOT NULL,
  `stawka_vat` decimal(5,2) DEFAULT 23.00,
  `data_modyfikacji` timestamp NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin2 COLLATE=latin2_general_ci;
CREATE TABLE `cennik_sygnaly` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `typ_programu` enum('Prognoza pogody','Serwis drogowy','Sponsor ogólny','Sponsor programu') NOT NULL,
  `stawka_netto` decimal(10,2) NOT NULL,
  `stawka_vat` decimal(5,2) DEFAULT 23.00,
  `data_modyfikacji` timestamp NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin2 COLLATE=latin2_general_ci;
CREATE TABLE `cennik_wywiady` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `nazwa` varchar(255) NOT NULL,
  `opis` text DEFAULT NULL,
  `stawka_netto` decimal(10,2) NOT NULL,
  `stawka_vat` decimal(5,2) DEFAULT 23.00,
  `data_modyfikacji` timestamp NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin2 COLLATE=latin2_general_ci;
CREATE TABLE `commission_types` (
  `code` varchar(32) NOT NULL,
  `name` varchar(150) NOT NULL,
  `sort_order` int(11) NOT NULL DEFAULT 0,
  `is_active` tinyint(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `communication_events` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `event_type` varchar(100) NOT NULL,
  `idempotency_key` varchar(191) NOT NULL,
  `direction` enum('outbound_client','internal','system') NOT NULL DEFAULT 'system',
  `status` enum('logged','sent','error','skipped_duplicate') NOT NULL DEFAULT 'logged',
  `recipient` text DEFAULT NULL,
  `subject` varchar(255) DEFAULT NULL,
  `body` mediumtext DEFAULT NULL,
  `meta_json` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`meta_json`)),
  `lead_id` int(11) DEFAULT NULL,
  `client_id` int(11) DEFAULT NULL,
  `campaign_id` int(11) DEFAULT NULL,
  `brief_id` int(11) DEFAULT NULL,
  `dispatch_id` int(11) DEFAULT NULL,
  `spot_audio_file_id` int(11) DEFAULT NULL,
  `created_by_user_id` int(11) DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_communication_events_idempotency` (`idempotency_key`),
  KEY `idx_communication_events_campaign_created` (`campaign_id`,`created_at`),
  KEY `idx_communication_events_client_created` (`client_id`,`created_at`),
  KEY `idx_communication_events_lead_created` (`lead_id`,`created_at`),
  KEY `idx_communication_events_type_created` (`event_type`,`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
CREATE TABLE `companies` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NOT NULL,
  `nip` varchar(20) DEFAULT NULL,
  `regon` varchar(50) DEFAULT NULL,
  `krs` varchar(50) DEFAULT NULL,
  `address` text DEFAULT NULL,
  `city` varchar(150) DEFAULT NULL,
  `postal_code` varchar(20) DEFAULT NULL,
  `province` varchar(150) DEFAULT NULL,
  `phone` varchar(50) DEFAULT NULL,
  `email` varchar(150) DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT current_timestamp(),
  `updated_at` datetime NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `gus_last_sid` varchar(100) DEFAULT NULL,
  `name_source` varchar(10) DEFAULT NULL,
  `address_source` varchar(10) DEFAULT NULL,
  `identifiers_source` varchar(10) DEFAULT NULL,
  `name_updated_at` datetime DEFAULT NULL,
  `address_updated_at` datetime DEFAULT NULL,
  `identifiers_updated_at` datetime DEFAULT NULL,
  `last_manual_update_at` datetime DEFAULT NULL,
  `last_gus_update_at` datetime DEFAULT NULL,
  `gus_hold_until` datetime DEFAULT NULL,
  `gus_hold_reason` varchar(20) DEFAULT NULL,
  `gus_not_found` tinyint(1) NOT NULL DEFAULT 0,
  `gus_not_found_at` datetime DEFAULT NULL,
  `gus_fail_streak` int(11) NOT NULL DEFAULT 0,
  `gus_last_error_class` varchar(20) DEFAULT NULL,
  `name_full` varchar(255) DEFAULT NULL,
  `name_short` varchar(255) DEFAULT NULL,
  `status` varchar(50) DEFAULT NULL,
  `is_active` tinyint(1) NOT NULL DEFAULT 1,
  `gus_last_refresh_at` datetime DEFAULT NULL,
  `gus_last_status` varchar(10) DEFAULT NULL,
  `gus_last_error_code` varchar(50) DEFAULT NULL,
  `gus_last_error_message` text DEFAULT NULL,
  `street` varchar(150) DEFAULT NULL,
  `building_no` varchar(30) DEFAULT NULL,
  `apartment_no` varchar(30) DEFAULT NULL,
  `gmina` varchar(150) DEFAULT NULL,
  `powiat` varchar(150) DEFAULT NULL,
  `wojewodztwo` varchar(150) DEFAULT NULL,
  `country` varchar(80) DEFAULT NULL,
  `lock_name` tinyint(1) NOT NULL DEFAULT 0,
  `lock_address` tinyint(1) NOT NULL DEFAULT 0,
  `lock_identifiers` tinyint(1) NOT NULL DEFAULT 0,
  `last_gus_check_at` datetime DEFAULT NULL,
  `last_gus_error_at` datetime DEFAULT NULL,
  `last_gus_error_message` text DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_companies_nip` (`nip`),
  KEY `idx_companies_nip` (`nip`),
  KEY `idx_companies_regon` (`regon`),
  KEY `idx_companies_krs` (`krs`),
  KEY `idx_companies_gus_hold_until` (`gus_hold_until`),
  KEY `idx_companies_gus_not_found` (`gus_not_found`),
  CONSTRAINT `chk_companies_name_source` CHECK (`name_source` in ('manual','gus') or `name_source` is null),
  CONSTRAINT `chk_companies_address_source` CHECK (`address_source` in ('manual','gus') or `address_source` is null),
  CONSTRAINT `chk_companies_identifiers_source` CHECK (`identifiers_source` in ('manual','gus') or `identifiers_source` is null),
  CONSTRAINT `chk_companies_nip_len` CHECK (`nip` is null or char_length(`nip`) = 10),
  CONSTRAINT `chk_companies_regon_len` CHECK (`regon` is null or char_length(`regon`) in (9,14)),
  CONSTRAINT `chk_companies_krs_len` CHECK (`krs` is null or char_length(`krs`) = 10)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `crm_aktywnosci` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `obiekt_typ` enum('lead','klient') NOT NULL,
  `obiekt_id` int(11) NOT NULL,
  `typ` enum('status','notatka','mail','system','email_in','email_out','sms_in','sms_out') NOT NULL,
  `status_id` int(11) DEFAULT NULL,
  `temat` varchar(255) DEFAULT NULL,
  `tresc` mediumtext DEFAULT NULL,
  `user_id` int(11) NOT NULL,
  `meta_json` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`meta_json`)),
  `created_at` datetime NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `idx_crm_aktywnosci_obiekt` (`obiekt_typ`,`obiekt_id`,`created_at`),
  KEY `idx_crm_aktywnosci_user` (`user_id`,`created_at`),
  KEY `idx_crm_aktywnosci_status` (`status_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
CREATE TABLE `crm_statusy` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `nazwa` varchar(80) NOT NULL,
  `aktywny` tinyint(1) NOT NULL DEFAULT 1,
  `dotyczy` enum('lead','klient','oba') NOT NULL DEFAULT 'oba',
  `sort` int(11) NOT NULL DEFAULT 100,
  `created_at` datetime NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
CREATE TABLE `crm_zadania` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `obiekt_typ` enum('lead','klient','kampania') NOT NULL,
  `obiekt_id` int(11) NOT NULL,
  `owner_user_id` int(11) NOT NULL,
  `typ` enum('telefon','email','sms','spotkanie','inne') NOT NULL,
  `tytul` varchar(160) NOT NULL,
  `opis` text DEFAULT NULL,
  `due_at` datetime NOT NULL,
  `status` enum('OPEN','DONE','CANCELLED') NOT NULL DEFAULT 'OPEN',
  `external_key` varchar(191) DEFAULT NULL,
  `done_at` datetime DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT current_timestamp(),
  `updated_at` datetime NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `idx_crm_zadania_owner_status_due` (`owner_user_id`,`status`,`due_at`),
  KEY `idx_crm_zadania_obiekt_due` (`obiekt_typ`,`obiekt_id`,`due_at`),
  KEY `idx_crm_zadania_external_status` (`external_key`,`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
CREATE TABLE `dokumenty` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `doc_type` varchar(30) NOT NULL,
  `doc_number` varchar(50) NOT NULL,
  `client_id` int(11) NOT NULL,
  `kampania_id` int(11) DEFAULT NULL,
  `created_by_user_id` int(11) NOT NULL,
  `stored_filename` varchar(255) NOT NULL,
  `original_filename` varchar(255) NOT NULL,
  `sha256` char(64) DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `doc_number` (`doc_number`),
  KEY `idx_dokumenty_client` (`client_id`),
  KEY `idx_dokumenty_kampania` (`kampania_id`),
  KEY `idx_dokumenty_user` (`created_by_user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `emisje` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `kampania_id` int(11) NOT NULL,
  `dzien` enum('pon','wt','sr','czw','pt','sob','ndz') NOT NULL,
  `godzina` time NOT NULL,
  `liczba` int(11) NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  KEY `kampania_id` (`kampania_id`),
  CONSTRAINT `emisje_ibfk_1` FOREIGN KEY (`kampania_id`) REFERENCES `kampanie` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
CREATE TABLE `emisje_spotow` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `spot_id` int(11) NOT NULL,
  `dow` tinyint(4) NOT NULL,
  `godzina` time NOT NULL,
  `liczba` int(11) NOT NULL DEFAULT 1,
  `created_at` datetime DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `idx_emisje_spotow_spot_id` (`spot_id`),
  KEY `idx_emisje_spotow_dow` (`dow`),
  KEY `idx_emisje_spotow_godzina` (`godzina`),
  CONSTRAINT `fk_emisje_spotow_spot` FOREIGN KEY (`spot_id`) REFERENCES `spoty` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `gus_cache` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `nip` varchar(20) DEFAULT NULL,
  `regon` varchar(20) DEFAULT NULL,
  `data_json` longtext NOT NULL,
  `fetched_at` datetime NOT NULL DEFAULT current_timestamp(),
  `source` varchar(20) NOT NULL DEFAULT 'gus',
  PRIMARY KEY (`id`),
  KEY `idx_gus_cache_nip` (`nip`),
  KEY `idx_gus_cache_regon` (`regon`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `gus_refresh_queue` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `company_id` int(11) NOT NULL,
  `priority` tinyint(4) NOT NULL DEFAULT 5,
  `reason` varchar(50) DEFAULT NULL,
  `status` varchar(20) NOT NULL DEFAULT 'pending',
  `attempts` int(11) NOT NULL DEFAULT 0,
  `max_attempts` int(11) NOT NULL DEFAULT 3,
  `next_run_at` datetime NOT NULL,
  `locked_at` datetime DEFAULT NULL,
  `locked_by` varchar(50) DEFAULT NULL,
  `last_error_code` varchar(50) DEFAULT NULL,
  `last_error_message` text DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT current_timestamp(),
  `updated_at` datetime NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `finished_at` datetime DEFAULT NULL,
  `error_class` varchar(20) DEFAULT NULL,
  `error_code` varchar(50) DEFAULT NULL,
  `error_message` text DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_queue_status_next` (`status`,`next_run_at`,`priority`),
  KEY `idx_queue_company` (`company_id`),
  KEY `idx_queue_company_status` (`company_id`,`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
CREATE TABLE `gus_snapshots` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `company_id` int(11) DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT current_timestamp(),
  `env` varchar(10) NOT NULL,
  `request_type` varchar(10) NOT NULL,
  `request_value` varchar(32) NOT NULL,
  `report_type` varchar(80) DEFAULT NULL,
  `http_code` int(11) DEFAULT NULL,
  `ok` tinyint(1) NOT NULL DEFAULT 0,
  `error_code` varchar(50) DEFAULT NULL,
  `error_message` text DEFAULT NULL,
  `fault_code` varchar(100) DEFAULT NULL,
  `fault_string` text DEFAULT NULL,
  `raw_request` longtext DEFAULT NULL,
  `raw_response` longtext DEFAULT NULL,
  `raw_parsed` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`raw_parsed`)),
  `correlation_id` varchar(100) DEFAULT NULL,
  `attempt_no` int(11) DEFAULT NULL,
  `latency_ms` int(11) DEFAULT NULL,
  `error_class` varchar(20) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_gus_snapshots_company` (`company_id`),
  KEY `idx_gus_snapshots_env` (`env`),
  KEY `idx_gus_snapshots_request_value` (`request_value`),
  KEY `idx_gus_snapshots_created_at` (`created_at`),
  KEY `idx_gus_snapshots_ok` (`ok`),
  KEY `idx_gus_snapshots_company_created` (`company_id`,`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
CREATE TABLE `historia_maili_ofert` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `kampania_id` int(11) NOT NULL,
  `klient_id` int(11) DEFAULT NULL,
  `user_id` int(11) NOT NULL,
  `to_email` varchar(255) NOT NULL,
  `subject` varchar(255) NOT NULL,
  `status` varchar(20) NOT NULL,
  `error_msg` text DEFAULT NULL,
  `sent_at` datetime NOT NULL DEFAULT current_timestamp(),
  `lead_id` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `kampania_id` (`kampania_id`),
  KEY `user_id` (`user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
CREATE TABLE `integration_alerts` (
  `alert_key` varchar(80) NOT NULL,
  `last_logged_at` datetime NOT NULL,
  `last_payload` text DEFAULT NULL,
  PRIMARY KEY (`alert_key`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
CREATE TABLE `integration_circuit_breaker` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `integration` varchar(30) NOT NULL,
  `state` varchar(20) NOT NULL,
  `reason` varchar(50) DEFAULT NULL,
  `details` text DEFAULT NULL,
  `degraded_until` datetime DEFAULT NULL,
  `updated_at` datetime NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `integration` (`integration`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
CREATE TABLE `integrations_logs` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `log_time` datetime NOT NULL DEFAULT current_timestamp(),
  `user_id` int(11) DEFAULT NULL,
  `type` varchar(30) NOT NULL,
  `request_id` varchar(100) DEFAULT NULL,
  `message` text NOT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_integrations_logs_type` (`type`),
  KEY `idx_integrations_logs_user` (`user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `kampanie` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `klient_id` int(11) DEFAULT NULL,
  `klient_nazwa` varchar(255) DEFAULT NULL,
  `dlugosc_spotu` int(11) DEFAULT NULL,
  `data_start` date DEFAULT NULL,
  `data_koniec` date DEFAULT NULL,
  `rabat` decimal(5,2) DEFAULT 0.00,
  `netto_spoty` decimal(10,2) DEFAULT NULL,
  `netto_dodatki` decimal(10,2) DEFAULT NULL,
  `razem_netto` decimal(10,2) DEFAULT NULL,
  `razem_brutto` decimal(10,2) DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT current_timestamp(),
  `propozycja` tinyint(1) DEFAULT 0,
  `audio_file` varchar(255) DEFAULT NULL,
  `owner_user_id` int(11) DEFAULT NULL,
  `status` varchar(50) NOT NULL DEFAULT 'W realizacji',
  `wartosc_netto` decimal(12,2) NOT NULL DEFAULT 0.00,
  `source_lead_id` int(11) DEFAULT NULL,
  `realization_status` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_kampanie_owner_user_id` (`owner_user_id`),
  KEY `idx_kampanie_created_at` (`created_at`),
  KEY `idx_kampanie_status` (`status`),
  KEY `idx_kampanie_data_start` (`data_start`),
  KEY `idx_kampanie_source_lead_id` (`source_lead_id`),
  KEY `idx_kampanie_realization_status` (`realization_status`)
) ENGINE=InnoDB DEFAULT CHARSET=latin2 COLLATE=latin2_general_ci;
CREATE TABLE `kampanie_emisje` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `kampania_id` int(11) NOT NULL,
  `dzien_tygodnia` enum('mon','tue','wed','thu','fri','sat','sun') DEFAULT NULL,
  `godzina` time DEFAULT NULL,
  `ilosc` int(11) DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `kampania_id` (`kampania_id`),
  CONSTRAINT `kampanie_emisje_ibfk_1` FOREIGN KEY (`kampania_id`) REFERENCES `kampanie` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=latin2 COLLATE=latin2_general_ci;
CREATE TABLE `kampanie_tygodniowe` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `klient_nazwa` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `nazwa_kampanii` varchar(255) DEFAULT NULL,
  `dlugosc` tinyint(3) unsigned NOT NULL,
  `data_start` date NOT NULL,
  `data_koniec` date NOT NULL,
  `sumy` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  `produkty` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  `netto_spoty` decimal(10,2) NOT NULL DEFAULT 0.00,
  `netto_dodatki` decimal(10,2) NOT NULL DEFAULT 0.00,
  `rabat` decimal(5,2) NOT NULL DEFAULT 0.00,
  `razem_po_rabacie` decimal(10,2) NOT NULL DEFAULT 0.00,
  `razem_brutto` decimal(10,2) NOT NULL DEFAULT 0.00,
  `siatka` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` datetime DEFAULT NULL,
  `audio_file` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `owner_user_id` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_okres` (`data_start`,`data_koniec`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
CREATE TABLE `klienci` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `nazwa_firmy` varchar(255) DEFAULT NULL,
  `nip` varchar(20) DEFAULT NULL,
  `regon` varchar(50) DEFAULT NULL,
  `adres` varchar(255) DEFAULT NULL,
  `data_dodania` timestamp NULL DEFAULT current_timestamp(),
  `ulica` varchar(255) DEFAULT NULL,
  `nr_nieruchomosci` varchar(20) DEFAULT NULL,
  `nr_lokalu` varchar(20) DEFAULT NULL,
  `kod_pocztowy` varchar(20) DEFAULT NULL,
  `miejscowosc` varchar(100) DEFAULT NULL,
  `wojewodztwo` varchar(100) DEFAULT NULL,
  `powiat` varchar(100) DEFAULT NULL,
  `gmina` varchar(100) DEFAULT NULL,
  `kraj` varchar(100) DEFAULT NULL,
  `telefon` varchar(50) DEFAULT NULL,
  `email` varchar(100) DEFAULT NULL,
  `strona_www` varchar(255) DEFAULT NULL,
  `status` varchar(50) DEFAULT 'Nowy',
  `ostatni_kontakt` date DEFAULT NULL,
  `notatka` text DEFAULT NULL,
  `potencjal` decimal(10,2) DEFAULT NULL,
  `przypomnienie` date DEFAULT NULL,
  `branza` varchar(255) DEFAULT NULL,
  `owner_user_id` int(11) DEFAULT NULL,
  `source_lead_id` int(11) DEFAULT NULL,
  `assigned_user_id` int(11) DEFAULT NULL,
  `kontakt_imie_nazwisko` varchar(120) DEFAULT NULL,
  `kontakt_stanowisko` varchar(120) DEFAULT NULL,
  `kontakt_telefon` varchar(60) DEFAULT NULL,
  `kontakt_email` varchar(120) DEFAULT NULL,
  `kontakt_preferencja` enum('telefon','email','sms','') NOT NULL DEFAULT '',
  `company_id` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `nip` (`nip`),
  KEY `idx_klienci_owner_user_id` (`owner_user_id`),
  KEY `idx_klienci_source_lead_id` (`source_lead_id`),
  KEY `idx_klienci_assigned_user_id` (`assigned_user_id`),
  KEY `idx_klienci_company_id` (`company_id`),
  CONSTRAINT `fk_klienci_company` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin2 COLLATE=latin2_general_ci;
CREATE TABLE `konfiguracja_systemu` (
  `id` int(11) NOT NULL DEFAULT 1,
  `liczba_blokow` int(11) NOT NULL DEFAULT 2,
  `godzina_start` time NOT NULL DEFAULT '07:00:00',
  `godzina_koniec` time NOT NULL DEFAULT '21:00:00',
  `prog_procentowy` enum('0','2','7','12','20') NOT NULL DEFAULT '2',
  `prime_hours` varchar(255) DEFAULT NULL,
  `standard_hours` varchar(255) DEFAULT NULL,
  `night_hours` varchar(255) DEFAULT NULL,
  `pdf_logo_path` varchar(255) DEFAULT NULL,
  `smtp_host` varchar(255) DEFAULT NULL,
  `smtp_port` int(11) DEFAULT NULL,
  `smtp_secure` varchar(10) DEFAULT NULL,
  `smtp_auth` tinyint(1) DEFAULT NULL,
  `smtp_default_from_email` varchar(255) DEFAULT NULL,
  `smtp_default_from_name` varchar(255) DEFAULT NULL,
  `smtp_username` varchar(255) DEFAULT NULL,
  `smtp_password` varchar(255) DEFAULT NULL,
  `email_signature_template_html` longtext DEFAULT NULL,
  `limit_prime_seconds_per_day` int(11) NOT NULL DEFAULT 3600,
  `limit_standard_seconds_per_day` int(11) NOT NULL DEFAULT 3600,
  `limit_night_seconds_per_day` int(11) NOT NULL DEFAULT 3600,
  `maintenance_last_run_at` datetime DEFAULT NULL,
  `maintenance_interval_minutes` int(11) NOT NULL DEFAULT 10,
  `audio_upload_max_mb` int(11) NOT NULL DEFAULT 50,
  `audio_allowed_ext` varchar(100) NOT NULL DEFAULT 'wav,mp3',
  `gus_enabled` tinyint(1) NOT NULL DEFAULT 0,
  `gus_api_key` varchar(255) DEFAULT NULL,
  `gus_environment` varchar(20) NOT NULL DEFAULT 'prod',
  `gus_cache_ttl_days` int(11) NOT NULL DEFAULT 30,
  `company_name` varchar(255) DEFAULT NULL,
  `company_address` varchar(255) DEFAULT NULL,
  `company_nip` varchar(50) DEFAULT NULL,
  `company_email` varchar(255) DEFAULT NULL,
  `company_phone` varchar(50) DEFAULT NULL,
  `documents_storage_path` varchar(255) DEFAULT NULL,
  `documents_number_prefix` varchar(50) NOT NULL DEFAULT 'AM/',
  `gus_auto_refresh_enabled` tinyint(1) NOT NULL DEFAULT 0,
  `gus_auto_refresh_batch` int(11) NOT NULL DEFAULT 20,
  `gus_auto_refresh_interval_days` int(11) NOT NULL DEFAULT 30,
  `gus_auto_refresh_backoff_minutes` int(11) NOT NULL DEFAULT 60,
  `crm_archive_bcc_email` varchar(255) DEFAULT NULL,
  `crm_archive_enabled` tinyint(1) NOT NULL DEFAULT 0,
  `block_duration_seconds` int(11) NOT NULL DEFAULT 45,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin2 COLLATE=latin2_general_ci;
CREATE TABLE `koszty_dodatkowe` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `nazwa_kosztu` varchar(255) NOT NULL,
  `kwota_netto` decimal(10,2) NOT NULL,
  `opis` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin2 COLLATE=latin2_general_ci;
CREATE TABLE `lead_briefs` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `campaign_id` int(11) NOT NULL,
  `lead_id` int(11) DEFAULT NULL,
  `token` char(64) NOT NULL,
  `status` enum('draft','sent','submitted','approved_internal') NOT NULL DEFAULT 'draft',
  `is_customer_editable` tinyint(1) NOT NULL DEFAULT 1,
  `spot_length_seconds` int(11) DEFAULT NULL,
  `lector_count` int(11) DEFAULT NULL,
  `target_group` text DEFAULT NULL,
  `main_message` text DEFAULT NULL,
  `additional_info` text DEFAULT NULL,
  `contact_details` text DEFAULT NULL,
  `tone_style` text DEFAULT NULL,
  `sound_effects` text DEFAULT NULL,
  `notes` text DEFAULT NULL,
  `production_owner_user_id` int(11) DEFAULT NULL,
  `production_external_studio` varchar(255) DEFAULT NULL,
  `submitted_at` datetime DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT current_timestamp(),
  `updated_at` datetime NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_lead_briefs_campaign_id` (`campaign_id`),
  UNIQUE KEY `uq_lead_briefs_token` (`token`),
  KEY `idx_lead_briefs_lead_id` (`lead_id`),
  KEY `idx_lead_briefs_status` (`status`),
  KEY `idx_lead_briefs_production_owner` (`production_owner_user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
CREATE TABLE `leady` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `nazwa_firmy` varchar(255) NOT NULL,
  `nip` varchar(20) DEFAULT NULL,
  `telefon` varchar(50) DEFAULT NULL,
  `email` varchar(255) DEFAULT NULL,
  `zrodlo` enum('telefon','email','formularz_www','maps_api','polecenie','inne') NOT NULL DEFAULT 'inne',
  `przypisany_handlowiec` varchar(255) DEFAULT NULL,
  `status` varchar(50) NOT NULL DEFAULT 'nowy',
  `notatki` text DEFAULT NULL,
  `next_action_date` date DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `owner_user_id` int(11) DEFAULT NULL,
  `priority` varchar(20) NOT NULL DEFAULT 'Średni',
  `next_action` varchar(255) DEFAULT NULL,
  `next_action_at` datetime DEFAULT NULL,
  `client_id` int(11) DEFAULT NULL,
  `converted_at` datetime DEFAULT NULL,
  `converted_by_user_id` int(11) DEFAULT NULL,
  `assigned_user_id` int(11) DEFAULT NULL,
  `kontakt_imie_nazwisko` varchar(120) DEFAULT NULL,
  `kontakt_stanowisko` varchar(120) DEFAULT NULL,
  `kontakt_telefon` varchar(60) DEFAULT NULL,
  `kontakt_email` varchar(120) DEFAULT NULL,
  `kontakt_preferencja` enum('telefon','email','sms','') NOT NULL DEFAULT '',
  `kod_pocztowy` varchar(12) DEFAULT NULL,
  `miasto` varchar(120) DEFAULT NULL,
  `ulica` varchar(180) DEFAULT NULL,
  `nr_budynku` varchar(30) DEFAULT NULL,
  `nr_lokalu` varchar(30) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_leady_status` (`status`),
  KEY `idx_leady_zrodlo` (`zrodlo`),
  KEY `idx_leady_nip` (`nip`),
  KEY `idx_leady_created_at` (`created_at`),
  KEY `idx_leady_owner_user_id` (`owner_user_id`),
  KEY `idx_leady_client_id` (`client_id`),
  KEY `idx_leady_next_action_at` (`next_action_at`),
  KEY `idx_leady_converted_at` (`converted_at`),
  KEY `idx_leady_assigned_user_id` (`assigned_user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
CREATE TABLE `leady_aktywnosci` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `lead_id` int(11) NOT NULL,
  `user_id` int(11) NOT NULL,
  `typ` varchar(30) NOT NULL,
  `opis` text DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `lead_id` (`lead_id`),
  KEY `user_id` (`user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `mail_accounts` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `user_id` int(11) NOT NULL,
  `imap_host` varchar(255) NOT NULL,
  `imap_port` int(11) NOT NULL DEFAULT 993,
  `imap_encryption` enum('ssl','tls','none') NOT NULL DEFAULT 'ssl',
  `smtp_host` varchar(255) NOT NULL,
  `smtp_port` int(11) NOT NULL DEFAULT 587,
  `smtp_encryption` enum('ssl','tls','none') NOT NULL DEFAULT 'tls',
  `email_address` varchar(255) NOT NULL,
  `username` varchar(255) NOT NULL,
  `password_enc` text DEFAULT NULL,
  `is_active` tinyint(1) NOT NULL DEFAULT 1,
  `last_sync_at` datetime DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT current_timestamp(),
  `imap_mailbox` varchar(255) NOT NULL DEFAULT 'INBOX',
  `smtp_from_name` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_mail_accounts_user` (`user_id`),
  UNIQUE KEY `uniq_mail_user` (`user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
CREATE TABLE `mail_attachments` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `mail_message_id` int(11) NOT NULL,
  `filename` varchar(255) NOT NULL,
  `stored_path` varchar(512) NOT NULL,
  `mime_type` varchar(100) DEFAULT NULL,
  `size_bytes` int(11) DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT current_timestamp(),
  `storage_path` varchar(500) NOT NULL DEFAULT '',
  PRIMARY KEY (`id`),
  KEY `idx_mail_attachments_message` (`mail_message_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
CREATE TABLE `mail_messages` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `client_id` int(11) DEFAULT NULL,
  `lead_id` int(11) DEFAULT NULL,
  `campaign_id` int(11) DEFAULT NULL,
  `owner_user_id` int(11) NOT NULL,
  `direction` enum('in','out') NOT NULL,
  `from_email` varchar(255) DEFAULT NULL,
  `from_name` varchar(255) DEFAULT NULL,
  `to_email` text DEFAULT NULL,
  `cc_email` text DEFAULT NULL,
  `bcc_email` text DEFAULT NULL,
  `subject` varchar(255) DEFAULT NULL,
  `body_html` mediumtext DEFAULT NULL,
  `body_text` mediumtext DEFAULT NULL,
  `status` enum('SENT','ERROR','RECEIVED') NOT NULL DEFAULT 'SENT',
  `error_message` text DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT current_timestamp(),
  `message_id` varchar(255) NOT NULL,
  `in_reply_to` varchar(255) DEFAULT NULL,
  `references_header` text DEFAULT NULL,
  `imap_uid` int(11) DEFAULT NULL,
  `imap_mailbox` varchar(255) DEFAULT NULL,
  `received_at` datetime DEFAULT NULL,
  `mail_account_id` int(11) NOT NULL DEFAULT 0,
  `thread_id` int(11) DEFAULT NULL,
  `to_emails` text DEFAULT NULL,
  `cc_emails` text DEFAULT NULL,
  `sent_at` datetime DEFAULT NULL,
  `has_attachments` tinyint(1) NOT NULL DEFAULT 0,
  `entity_type` enum('lead','client') DEFAULT NULL,
  `entity_id` int(11) DEFAULT NULL,
  `created_by_user_id` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_mail_messages_account_message` (`mail_account_id`,`message_id`),
  KEY `idx_mail_messages_owner_created` (`owner_user_id`,`created_at`),
  KEY `idx_mail_messages_client_created` (`client_id`,`created_at`),
  KEY `idx_mail_messages_campaign_created` (`campaign_id`,`created_at`),
  KEY `idx_mail_messages_owner_imap_uid` (`owner_user_id`,`imap_uid`,`imap_mailbox`),
  KEY `idx_mail_messages_message_id` (`message_id`),
  KEY `idx_mail_messages_entity_created` (`entity_type`,`entity_id`,`created_at`),
  KEY `idx_mail_messages_thread_created` (`thread_id`,`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
CREATE TABLE `mail_threads` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `entity_type` enum('lead','client') NOT NULL,
  `entity_id` int(11) NOT NULL,
  `subject` varchar(255) DEFAULT NULL,
  `subject_hash` char(64) NOT NULL,
  `last_message_at` datetime NOT NULL,
  `created_at` datetime NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `idx_mail_threads_entity_last` (`entity_type`,`entity_id`,`last_message_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
CREATE TABLE `numeracja_dokumentow` (
  `year` int(11) NOT NULL,
  `last_number` int(11) NOT NULL DEFAULT 0,
  PRIMARY KEY (`year`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `plany_emisji` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `klient_id` int(11) NOT NULL,
  `rok` int(11) NOT NULL,
  `miesiac` int(11) NOT NULL,
  `nazwa_planu` varchar(255) NOT NULL,
  `dlugosc_spotu` time DEFAULT NULL,
  `rabat` decimal(10,2) DEFAULT 0.00,
  `data_utworzenia` timestamp NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `klient_id` (`klient_id`),
  CONSTRAINT `plany_emisji_ibfk_1` FOREIGN KEY (`klient_id`) REFERENCES `klienci` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=latin2 COLLATE=latin2_general_ci;
CREATE TABLE `plany_emisji_szczegoly` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `plan_id` int(11) NOT NULL,
  `dzien_miesiaca` int(11) NOT NULL,
  `godzina` time NOT NULL,
  `ilosc_spotow` int(11) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `plan_id` (`plan_id`),
  CONSTRAINT `plany_emisji_szczegoly_ibfk_1` FOREIGN KEY (`plan_id`) REFERENCES `plany_emisji` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=latin2 COLLATE=latin2_general_ci;
CREATE TABLE `powiadomienia` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `user_id` int(11) NOT NULL,
  `typ` varchar(30) NOT NULL,
  `tresc` text NOT NULL,
  `link` varchar(255) DEFAULT NULL,
  `is_read` tinyint(1) NOT NULL DEFAULT 0,
  `created_at` datetime NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `idx_powiadomienia_user` (`user_id`),
  KEY `idx_powiadomienia_type` (`typ`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `prowizje_rozliczenia` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `year` smallint(6) NOT NULL,
  `month` tinyint(4) NOT NULL,
  `user_id` int(11) NOT NULL,
  `rate_percent` decimal(5,2) NOT NULL,
  `base_netto` decimal(12,2) NOT NULL DEFAULT 0.00,
  `commission_netto` decimal(12,2) NOT NULL DEFAULT 0.00,
  `status` varchar(20) NOT NULL DEFAULT 'Należne',
  `calculated_at` datetime NOT NULL DEFAULT current_timestamp(),
  `paid_at` datetime DEFAULT NULL,
  `note` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_prowizje_rozliczenia_period_user` (`year`,`month`,`user_id`),
  KEY `idx_prowizje_rozliczenia_user` (`user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `schema_migrations` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `filename` varchar(255) NOT NULL,
  `applied_at` datetime NOT NULL DEFAULT current_timestamp(),
  `checksum` char(64) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_schema_migrations_filename` (`filename`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
CREATE TABLE `app_meta` (
  `id` tinyint(3) unsigned NOT NULL,
  `install_state` varchar(32) NOT NULL,
  `installed_version` varchar(64) DEFAULT NULL,
  `installed_at` datetime DEFAULT NULL,
  `baseline_id` varchar(128) DEFAULT NULL,
  `release_channel` varchar(32) DEFAULT NULL,
  `last_update_check_at` datetime DEFAULT NULL,
  `last_update_check_status` varchar(32) DEFAULT NULL,
  `last_update_check_error` text DEFAULT NULL,
  `last_available_version` varchar(64) DEFAULT NULL,
  `last_available_published_at` datetime DEFAULT NULL,
  `last_available_notes_url` varchar(255) DEFAULT NULL,
  `last_manifest_url` varchar(255) DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT current_timestamp(),
  `updated_at` datetime NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
CREATE TABLE `sms_messages` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `entity_type` enum('lead','client') DEFAULT NULL,
  `entity_id` int(11) DEFAULT NULL,
  `user_id` int(11) DEFAULT NULL,
  `direction` enum('in','out') NOT NULL,
  `phone` varchar(40) NOT NULL,
  `content` text NOT NULL,
  `provider` varchar(50) DEFAULT NULL,
  `provider_message_id` varchar(120) DEFAULT NULL,
  `status` varchar(40) DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `idx_sms_messages_entity_created` (`entity_type`,`entity_id`,`created_at`),
  KEY `idx_sms_messages_phone_created` (`phone`,`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
CREATE TABLE `spot_audio_dispatch_items` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `dispatch_id` int(11) NOT NULL,
  `spot_audio_file_id` int(11) NOT NULL,
  `created_at` datetime NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_spot_audio_dispatch_items_unique` (`dispatch_id`,`spot_audio_file_id`),
  KEY `idx_spot_audio_dispatch_items_dispatch` (`dispatch_id`),
  KEY `idx_spot_audio_dispatch_items_audio` (`spot_audio_file_id`),
  CONSTRAINT `fk_spot_audio_dispatch_items_audio` FOREIGN KEY (`spot_audio_file_id`) REFERENCES `spot_audio_files` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_spot_audio_dispatch_items_dispatch` FOREIGN KEY (`dispatch_id`) REFERENCES `spot_audio_dispatches` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
CREATE TABLE `spot_audio_dispatches` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `campaign_id` int(11) NOT NULL,
  `spot_id` int(11) NOT NULL,
  `dispatched_by_user_id` int(11) NOT NULL,
  `dispatched_at` datetime NOT NULL DEFAULT current_timestamp(),
  `channel` varchar(30) NOT NULL DEFAULT 'manual',
  `note` varchar(255) DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `idx_spot_audio_dispatches_campaign` (`campaign_id`),
  KEY `idx_spot_audio_dispatches_spot` (`spot_id`),
  KEY `idx_spot_audio_dispatches_dispatched_at` (`dispatched_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
CREATE TABLE `spot_audio_files` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `spot_id` int(11) NOT NULL,
  `version_no` int(11) NOT NULL DEFAULT 1,
  `is_active` tinyint(1) NOT NULL DEFAULT 1,
  `original_filename` varchar(255) NOT NULL,
  `stored_filename` varchar(255) NOT NULL,
  `mime_type` varchar(100) DEFAULT NULL,
  `file_size` int(11) DEFAULT NULL,
  `sha256` char(64) DEFAULT NULL,
  `production_status` varchar(30) NOT NULL DEFAULT 'Do akceptacji',
  `approved_by_user_id` int(11) DEFAULT NULL,
  `approved_at` datetime DEFAULT NULL,
  `rejection_reason` varchar(255) DEFAULT NULL,
  `uploaded_by_user_id` int(11) NOT NULL,
  `upload_note` varchar(255) DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT current_timestamp(),
  `is_final` tinyint(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_spot_audio_files_stored` (`stored_filename`),
  KEY `idx_spot_audio_files_spot_id` (`spot_id`),
  KEY `idx_spot_audio_files_uploaded_by` (`uploaded_by_user_id`),
  KEY `idx_spot_audio_files_spot_final` (`spot_id`,`is_final`),
  KEY `idx_spot_audio_files_spot_active_status` (`spot_id`,`is_active`,`production_status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `spoty` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `klient_id` int(11) DEFAULT NULL,
  `nazwa_spotu` varchar(255) NOT NULL,
  `dlugosc` enum('15','20','30') NOT NULL,
  `data_start` date DEFAULT NULL,
  `data_koniec` date DEFAULT NULL,
  `data_dodania` timestamp NULL DEFAULT current_timestamp(),
  `aktywny` tinyint(1) NOT NULL DEFAULT 1,
  `rezerwacja` tinyint(1) NOT NULL DEFAULT 0,
  `kampania_id` int(11) DEFAULT NULL,
  `dlugosc_s` int(11) NOT NULL DEFAULT 30,
  `status` varchar(20) NOT NULL DEFAULT 'Aktywny',
  `rotation_group` varchar(1) DEFAULT NULL,
  `rotation_mode` varchar(30) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `klient_id` (`klient_id`),
  KEY `idx_spoty_klient_id` (`klient_id`),
  KEY `idx_spoty_kampania_id` (`kampania_id`),
  CONSTRAINT `spoty_ibfk_1` FOREIGN KEY (`klient_id`) REFERENCES `klienci` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=latin2 COLLATE=latin2_general_ci;
CREATE TABLE `spoty_emisje` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `spot_id` int(11) NOT NULL,
  `data` date NOT NULL,
  `godzina` time NOT NULL,
  `blok` varchar(1) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `spot_id` (`spot_id`),
  CONSTRAINT `spoty_emisje_ibfk_1` FOREIGN KEY (`spot_id`) REFERENCES `spoty` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=latin2 COLLATE=latin2_general_ci;
CREATE TABLE `system_logs` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `created_at` datetime NOT NULL DEFAULT current_timestamp(),
  `user_id` int(11) NOT NULL,
  `action` varchar(50) NOT NULL,
  `message` text NOT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_system_logs_user` (`user_id`),
  KEY `idx_system_logs_action` (`action`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `transactions` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `campaign_id` int(11) NOT NULL,
  `client_id` int(11) DEFAULT NULL,
  `source_lead_id` int(11) DEFAULT NULL,
  `owner_user_id` int(11) DEFAULT NULL,
  `value_netto` decimal(12,2) NOT NULL DEFAULT 0.00,
  `value_brutto` decimal(12,2) NOT NULL DEFAULT 0.00,
  `status` varchar(30) NOT NULL DEFAULT 'won',
  `won_at` datetime DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT current_timestamp(),
  `updated_at` datetime NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_transactions_campaign_id` (`campaign_id`),
  KEY `idx_transactions_owner_won_at` (`owner_user_id`,`won_at`),
  KEY `idx_transactions_status_won_at` (`status`,`won_at`),
  KEY `idx_transactions_client_id` (`client_id`),
  KEY `idx_transactions_source_lead_id` (`source_lead_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
CREATE TABLE `uzytkownicy` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `login` varchar(50) NOT NULL,
  `haslo_hash` varchar(255) NOT NULL,
  `rola` varchar(32) NOT NULL DEFAULT 'Handlowiec',
  `data_utworzenia` timestamp NULL DEFAULT current_timestamp(),
  `reset_token` varchar(255) DEFAULT NULL,
  `reset_token_expires` datetime DEFAULT NULL,
  `smtp_user` varchar(255) DEFAULT NULL,
  `smtp_pass` varchar(255) DEFAULT NULL,
  `smtp_from_email` varchar(255) DEFAULT NULL,
  `smtp_from_name` varchar(255) DEFAULT NULL,
  `email_signature` text DEFAULT NULL,
  `use_system_smtp` tinyint(1) NOT NULL DEFAULT 0,
  `email` varchar(255) DEFAULT NULL,
  `aktywny` tinyint(1) NOT NULL DEFAULT 1,
  `imie` varchar(100) DEFAULT NULL,
  `nazwisko` varchar(100) DEFAULT NULL,
  `telefon` varchar(50) DEFAULT NULL,
  `funkcja` varchar(150) DEFAULT NULL,
  `commission_enabled` tinyint(1) NOT NULL DEFAULT 0,
  `commission_rate_percent` decimal(5,2) NOT NULL DEFAULT 0.00,
  `prov_new_contract_pct` decimal(5,2) NOT NULL DEFAULT 0.00,
  `prov_renewal_pct` decimal(5,2) NOT NULL DEFAULT 0.00,
  `prov_next_invoice_pct` decimal(5,2) NOT NULL DEFAULT 0.00,
  `smtp_pass_enc` text DEFAULT NULL,
  `smtp_host` varchar(255) DEFAULT NULL,
  `smtp_port` int(11) DEFAULT NULL,
  `smtp_secure` varchar(10) NOT NULL DEFAULT 'tls',
  `smtp_enabled` tinyint(1) NOT NULL DEFAULT 0,
  `imap_host` varchar(255) DEFAULT NULL,
  `imap_port` int(11) DEFAULT NULL,
  `imap_user` varchar(255) DEFAULT NULL,
  `imap_pass_enc` text DEFAULT NULL,
  `imap_secure` varchar(10) NOT NULL DEFAULT 'tls',
  `imap_enabled` tinyint(1) NOT NULL DEFAULT 0,
  `imap_mailbox` varchar(255) NOT NULL DEFAULT 'INBOX',
  `imap_last_uid` int(11) DEFAULT NULL,
  `imap_last_sync_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `login` (`login`)
) ENGINE=InnoDB DEFAULT CHARSET=latin2 COLLATE=latin2_general_ci;
CREATE TABLE `worker_locks` (
  `name` varchar(50) NOT NULL,
  `locked_by` varchar(120) DEFAULT NULL,
  `locked_at` datetime DEFAULT NULL,
  `heartbeat_at` datetime DEFAULT NULL,
  `expires_at` datetime DEFAULT NULL,
  `meta_json` text DEFAULT NULL,
  PRIMARY KEY (`name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
